### ISSUE TITLE
Vencord crashes immediately.

### ISSUE THREAD

**Issue by WeAreCrews** [ScattrdBlade/customSounds#3]
### Vencord crashing immeadiately after installing the plugin
**I installed plugin and figured to start vencord, its loading and when its loaded its crashing immediately.**
![Discord_ZmXB0R5gj5](https://github.com/user-attachments/assets/0c13fe4c-57b7-4162-b4b0-aa6cefa75879)

**Comment by WeAreCrews** [comment]
Dev build is installed.

**Comment by ScattrdBlade** [comment]
I've recently gotten a few reports of the plugin not working. I'll look into it within the next few days.

**Comment by ScattrdBlade** [comment]
Just rolled an update that should fix it!
