### ISSUE TITLE
Its no worky anymore

### ISSUE THREAD

**Issue by Person7557** [ScattrdBlade/customSounds#4]
As per title, since 4 days ago it just suddenly stopped swapping sounds, and i was loving this customization of sounds as it was making this terrible app more bearable, please @ScattrdBlade please make it work again, i hate the default notification sound.

**Comment by ScattrdBlade** [comment]
I am aware of the issue and will look into it within the next few days.

**Comment by ScattrdBlade** [comment]
Just rolled an update that should fix it!
