### ISSUE TITLE
Start up sound customization missing

### ISSUE THREAD

**Issue by Person7557** [ScattrdBlade/customSounds#6]
Hello @ScattrdBlade, first of all, thank you for the fix of plugin, great christmas gift, and i hope your christmas is calm and cozy. 

I noticed **Three** issues with current version:

1. Missing start up sound/discordo replacement option
2.  outbound call replacement sound doesn't work.
3. Incoming calls sound also isn't getting replaced.

And also request if possible to make separate sound for mentions. Thank you for your great work.

**Comment by ScattrdBlade** [comment]
Hey, no problem, and thank you! I hope you had a Merry Christmas!

I just released an update that should've taken care of all those issues, along with a few new features. Thank you for the quick feedback! It helps me make the plugin as good as possible. If you run into any more issues, please do let me know!
